apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: stage-grpc-backendconfig
spec:
  healthCheck:
    port: 8080
    requestPath: /
    type: HTTP2
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: stage-api-backendconfig
spec:
  healthCheck:
    port: 1317
    requestPath: /node_info
    type: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: rpcnodes
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/backend-config: '{"ports":{"grpc":"stage-grpc-backendconfig","api":"stage-api-backendconfig"}}'
    cloud.google.com/neg: '{"ingress":true,"exposed_ports":{"26657":{},"1317":{},"9090":{}}}'
spec:
  type: ClusterIP
  selector:
    grouplb: validator
  ports:
  - protocol: TCP
    targetPort: 26656
    port: 26656
    name: p2p
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpc
  - protocol: TCP
    targetPort: 1317
    port: 1317
    name: api
  - protocol: TCP
    targetPort: 9090
    port: 9090
    name: grpc

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/backend-config: '{"grpc": "stage-grpc-backendconfig"}'
  name: rpcnodes-ext
spec:
  type: LoadBalancer
  selector:
    grouplb: validator
  # sessionAffinity: "ClientIP"
  ports:
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpc
  - protocol: TCP
    targetPort: 1317
    port: 1317
    name: api
  - protocol: TCP
    targetPort: 9090
    port: 9090
    name: grpc
